# productuoj docker-compose
# docker-compose 파일의 버전을 명시
version: "3"

services: # 서비스들의 시작
  # 앱 설정
  lion-app:
    depends_on:
      - db
    container_name: lion-app-dc
    build:
      context: lion_app
      dockerfile: Dockerfile # 사용할 도커 파일의 이름
    image: lion-app:0.5
    ports:
      - "8000:8000" # 앞쪽이 호스트 시스템의 포트 : 뒤쬑이 컨테이너의 포트
    volumes:
      - ./lion_app:/app
      - staticfiles:/var/www/html/static
    command:
      - "/start"
    env_file:
      - ./.envs/prod/django
      - ./.envs/prod/db
      - ./.envs/prod/server

  nginx:
    restart: always
    depends_on:
      - lion-app
    container_name: lion-nginx-dc
    build:
      context: .
      dockerfile: Dockerfile.nginx_ubt
      # args:
      #   LOCAL_IP: "110.165.17.207" # 원래는 도메인 주소 값
    image: lion-nginx
    ports:
      - "8888:80"
    volumes:
      - staticfiles:/var/www/html/static
    env_file: # nginx 컨테이너에도 같은 환경변수가 들어가게 됨
     - ./.envs/prod/server

  db:
    image: postgres:15
    env_file:
      - ./.envs/prod/db
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  staticfiles:
  postgres_data:

