# Local docker-compose
# docker-compose 파일의 버전을 명시
version: "3"

services: # 서비스들의 시작
  # 앱 설정
  lion-app:
    depends_on:
      - db
    container_name: lion-app-dc
    build:
      context: lion_app
      dockerfile: Dockerfile # 사용할 도커 파일의 이름
    image: lion-app:0.5
    ports:
      - "8000:8000" # 앞쪽이 호스트 시스템의 포트 : 뒤쬑이 컨테이너의 포트
    volumes:
      - ~/.aws:/root/.aws:ro # read only 
      - ./lion_app:/app
      - staticfiles:/var/www/html/static
    command:
      - "/start"
    env_file:
      - ./.envs/local/django
      - ./.envs/local/db
      - ./.envs/local/server
      - ./.envs/prod/ncp
    environment:
      - AWS_SECRET_NAME=like/lion/lecture

  nginx:
    restart: always
    depends_on: # depends_on 명령어로 실행 순서를 만들어준다
      - lion-app
    container_name: lion-nginx-dc
    build:
      context: .
      dockerfile: Dockerfile.nginx_ubt
      # args:
      #   LOCAL_IP: "110.165.17.207" # 원래는 도메인 주소 값
    image: lion-nginx
    ports:
      - "8888:80"
    volumes:
      - staticfiles:/var/www/html/static
    env_file: # nginx 컨테이너에도 같은 환경변수가 들어가게 됨
      - ./.envs/local/server

  db:
    container_name: postgres-db
    image: postgres:15
    env_file:
      - ./.envs/local/db
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # mongo:
  #   container_name: mongo
  #   image: mongo:latest
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongo_data:/data/db


volumes:
  staticfiles:
  postgres_data:
  # mongo_data:

