apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lion.fullname" . }}
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.configMap.django.DJANGO_SETTINGS_MODULE }}
  DJANGO_SECRET_KEY: {{ .Values.secret.django.DJANGO_SECRET_KEY | b64enc | quote }}
  DB_HOST: {{ include "lion.db.fullname" . }}
