name: CD using argocd

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

env:
    IMAGE: ${{ vars.NCP_CONTAINER_REGISTRY }}/lion-app
    IMAGE_TAG: ${{ vars.NCP_CONTAINER_REGISTRY }}/lion-app:latest
    TAG: ""

jobs:
  deploy:
    name: deploy the new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Helm repository
        uses: actions/checkout@v4
        with:
          repository: IvaninITworld/k8s_study
          ref: main
          token: ${{ secrets.PAT }}

      - name: Get version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Update appVersion in Chart.yaml
        run: |
          sed -ie 's/appVersion: ".*"/appVersion: "'${{ github.ref_name }}'"/g' lion/Chart.yaml
