name: CD using argocd

on:
  workflow_dispatch:
  release:
    types: [published]

env:
    IMAGE: ${{ vars.NCP_CONTAINER_REGISTRY }}/lion-app
    IMAGE_TAG: ${{ vars.NCP_CONTAINER_REGISTRY }}/lion-app:latest

jobs:
  deploy:
    name: deploy the new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Helm repository
        uses: actions/checkout@v3
        with:
          repository: IvaninITworld/k8s_study
          ref: main
          token: ${{ secrets.k8s_token }}

      - name: Update appVersion in Chart.yaml
        run: |
          sed -ie 's/appVersion: ".*"/appVersion: "'${{ github.event.release.tag_name }}'"/g' lion/Chart.yaml

      - name: Commit files
        run: |
          git config --local user.email "xormrdlsrks2@gmail.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "update tag"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.k8s_token }}
          repository: IvaninITworld/k8s_study
          branch: main
