name: CI

on:
    pull_request:
    push:
        branches:
            -   "main"
        tags:
            -   "*.*.*"

env:
    IMAGE: ${{ vars.NCP_CONTAINER_REGISTRY }}/lion-app
    IMAGE_TAG: ${{ vars.NCP_CONTAINER_REGISTRY }}/lion-app:latest

jobs:
    lint:
        name: Check lint (black)
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   uses: actions/setup-python@v4
                with:
                  python-version: '3.11' 

            -   name: Install black
                run: pip install black

            -   name: Check black
                run: black --check lion_app


    build:
        needs: lint
        name: Build Image
        runs-on: ubuntu-latest
        steps:
            # checkout to the branch and get the codes
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: test
                run: |
                    docker-compose -f docker-compose.test.yaml up --build -d
                    docker-compose -f docker-compose.test.yaml run lion-app python manage.py test

            -   name: post-test
                run: |
                    docker-compose -f docker-compose.test.yaml down

            # buildx - support amd64, arm64
            -   name: Set up Docker buildx
                uses: docker/setup-buildx-action@v2
            
            # NCP Login
            -   name: Login to NCR
                uses: docker/login-action@v2
                with:
                    # registry: where to login
                    registry: ${{ vars.NCP_CONTAINER_REGISTRY }}
                    username: ${{ secrets.NCP_ACCESS_KEY }}
                    password: ${{ secrets.NCP_SECRET_KEY }}
            
            # -   name: Bump version and push tag
            #     id: tag_version
            #     uses: mathieudutour/github-tag-action@v6.1
            #     with:
            #         github_token: ${{ secrets.GITHUB_TOKEN }}
            #         default_bump: false
            #         # fix: - patch, feat: - minor, BREAKING CHANGE: - major
            
            # -   name: Create a GitHub release
            #     uses: ncipollo/release-action@v1
            #     with:
            #         tag: ${{ steps.tag_version.outputs.new_tag }}
            #         name: Release ${{ steps.tag_version.outputs.new_tag }}
            #         body: ${{ steps.tag_version.outputs.changelog }}

            # -   name: create VERSION
            #     run: echo "VERSION=${{ steps.tag_version.outputs.new_tag }}" >> "$GITHUB_OUTPUT"

            -   name: Get current timestamp
                id: timestamp
                run: echo "timestamp=$(date '+%s')" >> "$GITHUB_OUTPUT"

            -   name: Get version
                if: startsWith(github.ref, 'refs/tags')
                id: version
                run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"


            -   name: Build and Push
                if: startsWith(github.ref, 'refs/heads')
                uses: docker/build-push-action@v4
                with:
                    context: lion_app
                    push: true
                    tags: ${{ env.IMAGE_TAG }},"${{ env.IMAGE }}:${{ steps.timestamp.outputs.timestamp }}"
                    platforms: linux/amd64,linux/arm64
            
            -   name: build-and-push
                if: startsWith(github.ref, 'refs/tags')
                uses: docker/build-push-action@v4
                with:
                    context: lion_app
                    tags: ${{ env.IMAGE_TAG }},"${{ env.IMAGE }}:${{ steps.version.outputs.VERSION }}"
                    push: true
                    platforms: linux/amd64,linux/arm64