name: CI

on:
    pull_request:
    push:
        branches:
            -   "main"

env:
    IMAGE: ${{ vars.NCP_CONTAINER_REGISTRY }}/lion-app
    IMAGE_TAG: ${{ vars.NCP_CONTAINER_REGISTRY }}/lion-app:latest

jobs:
    build:
        name: Build Image
        runs-on: ubuntu-latest
        steps:
            # checkout to the branch and get the codes
            -   name: Checkout code
                uses: actions/checkout@v3

            # buildx - support amd64, arm64
            -   name: Set up Docker buildx
                uses: docker/setup-buildx-action@v2
            
            # NCP Login
            -   name: Login to NCR
                uses: docker/login-action@v2
                with:
                    # registry: where to login
                    registry: ${{ vars.NCP_CONTAINER_REGISTRY }}
                    username: ${{ secrets.NCP_ACCESS_KEY }}
                    password: ${{ secrets.NCP_SECRET_KEY }}
            
            -   name: Get current timestamp
                id: timestamp
                run: echo "timestamp=$(date '+%s')" >> "$GITHUB_OUTPUT"

            -   name: Build and Push
                uses: docker/build-push-action@v4
                with:
                    context: lion_app # location where image will be built
                    push: false # This indicates push event
                    tags: ${{ env.IMAGE_TAG }},"${{ env.IMAGE }}:${{ steps.timestamp.outputs.timestamp }}"