name: lesson1

on:
  push:
  pull_request:


jobs:
  echo-event:
    name: echo event
    runs-on: ubuntu-latest
    steps:
      - name: get event
        run: echo "This event is ${{github.event_name}}"

      - name: echo github context
        run: echo "${{github.repositoryUrl}}"

  # docker-compose-build:
  #   name: docker compose build
  #   runs-on: ubuntu-latest
  #   steps:
  #       - uses: actions/checkout@v3
  #       - name: list files
  #         run: | 
  #           ls -al
  #       - name: build
  #         run: |
  #           docker-compose -f docker-compose.yml --build
  #       - name: Django run
  #         run: |
  #           docker-compose -f docker-compose.yml up -d

  docker-build:
    name: docker build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up Docker buildx
          uses: docker/setup-buildx-action@v2
        - name: Build and Export
          uses: docker/build-push-action@v4
          with:
            context: lion_app
            tags: lion-app:latest
            outputs: type=docker,dest=/tmp/lion_app.tar
        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: lion-app
            path: tmp/myimage.tar
        - name: docker images
          if: ${{ always() }}
          run: docker images lion-app


  docker-images:
    # Always execute the bleow
    if: ${{ always() }} 
    needs: docker-build
    name: docker images
    runs-on: ubuntu-latest
    steps:
        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
            name: lion-app
            path: /tmp
        - name: Load image
          run: |
            docker load --input /tmp/lion_app.tar
        - name: docker images
          run: |
            docker images lion-app