name: CD using Docker Image

on:
    push:
        branches:
            -
                main
jobs:
    # build image / push image to NCR
    # pull Image from NCR / Run new container with new image

    deployment:
        name: push to NCP container registry
        runs-on: ubuntu-latest
        steps:
            # checkout to the branch and get the codes
            - name: Checkout code
              uses: actions/checkout@v3

            # buildx - support amd64, arm64
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2
            
            # NCP Login
            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ secrets.NCP_CONTAINER_REGISTRY }}
                username: ${{ secrets.NCP_ACCESS_KEY }}
                password: ${{ secrets.NCP_SECRET_KEY }}
            
            - name: Build and Export
              uses: docker/build-push-action@v4
              with:
                context: lion_app # location where image will be built
                push: true
                tags: ${{ secrets.NCP_CONTAINER_REGISTRY }}/lion-app:latest
                # outputs: type=docker,dest=/tmp/lion_app.tar

            - name: git pull via SSH
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  script: |
                      cd dev_django_app
                      git pull
                      docker login ${{ secrets.NCP_CONTAINER_REGISTRY }}
                      docker pull ${{ secrets.NCP_CONTAINER_REGISTRY }}/lion-app:latest
                      docker-compose -f docker-compose.prod.yml up --build -d
    
    # pull_from_ncp:
    #     name: Connect to Server via SSH and pull from NCP
    #     needs: deployment
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: git pull via SSH
    #           uses: appleboy/ssh-action@v1.0.0
    #           with:
    #             host: ${{ secrets.HOST }}
    #             username: ${{ secrets.USERNAME }}
    #             password: ${{ secrets.PASSWORD }}
    #             script: |
    #                 cd dev_django_app
    #                 git pull
    #                 docker pull ${{ secrets.NCP_CONTAINER_REGISTRY }}/lion-app:latest
    #                 docker-compose -f docker-compose.prod.yml restart lion-app