name: lesson1

on:
  push:
  pull_request:


jobs:
  echo-event:
    name: echo event
    runs-on: ubuntu-latest
    steps:
      - name: get event
        run: echo "This event is ${{github.event_name}}"

      - name: echo github context
        run: echo "${{github.repositoryUrl}}"

  # docker-compose-build:
  #   name: docker compose build
  #   runs-on: ubuntu-latest
  #   steps:
  #       - uses: actions/checkout@v3
  #       - name: list files
  #         run: | 
  #           ls -al
  #       - name: build
  #         run: |
  #           docker-compose -f docker-compose.yml --build
  #       - name: Django run
  #         run: |
  #           docker-compose -f docker-compose.yml up -d

  docker-build:
    name: docker build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: build
          # continue-on-error: true # Continue even if build fails
          working-directory: lion_app # Define where to execute below code
          run: |
            docker build --tag lion-app .

        # - name: docker image
        #   run: docker images lion-app # To check if it is created
        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: myimage
            path: /tmp/myiamge.tar


  docker-images:
    # Always execute the bleow
    if: ${{ always() }} 
    needs: docker-build
    name: docker iamges
    runs-on: ubuntu-latest
    steps:
        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
            name: myimage
            path: /tmp

        - name: Load and run docker images
          run: |
            docker load --input /tmp/myimage.tar
            docker images lion-app