name: CD

on:
    push:
        branches:
            - main

jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: git pull via SSH
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                script: |
                    git pull
            - name: docker-compose restart
              run: |
                pwd
                docker-compose -f docker-compose.prod.yml restart
                docker ps


            


